pip este un utilitar folosit in linie de comanda

# pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

In [3]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
np.array(     [ 1, 2, 3 ]    )

array([1, 2, 3])

In [6]:
arr = np.array(     [ 1, 2, 3 ]    )
print(arr, type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [7]:
arr = np.array([ 1, 2, 3, 2.30, 32.332 ] )
print(arr, type(arr))

[ 1.     2.     3.     2.3   32.332] <class 'numpy.ndarray'>


In [8]:
arr = np.array([ 1, 2, 3, 2.30, 32.332, True, False ] )
print(arr, type(arr))

[ 1.     2.     3.     2.3   32.332  1.     0.   ] <class 'numpy.ndarray'>


In [9]:
arr = np.array([ 1, 2, 3, 2.30, 32.332, True, False, "seara", "zi", "bun" ] )
print(arr, type(arr))

['1' '2' '3' '2.3' '32.332' 'True' 'False' 'seara' 'zi' 'bun'] <class 'numpy.ndarray'>


In [10]:
arr = np.array([ 1, 2, 3, 2.30, 32.332, True, False, "seara", "zi", "bun" ] )
print(arr, type(arr), arr.dtype)

['1' '2' '3' '2.3' '32.332' 'True' 'False' 'seara' 'zi' 'bun'] <class 'numpy.ndarray'> <U32


In [11]:
arr = np.array([ 1, 2, 3, 2.30, 32.332, True, False ] )
print(arr, type(arr), arr.dtype)

[ 1.     2.     3.     2.3   32.332  1.     0.   ] <class 'numpy.ndarray'> float64


In [12]:
arr = np.array([ 1, 2, 3] )
print(arr, type(arr), arr.dtype)

[1 2 3] <class 'numpy.ndarray'> int64
