In [1]:
import numpy as np

In [2]:
arr = np.array([22, 44, 33, 11, 22])
arr

array([22, 44, 33, 11, 22])

In [3]:
arr + 2

array([24, 46, 35, 13, 24])

In [4]:
arr + arr

array([44, 88, 66, 22, 44])

In [5]:
lista = [22, 44, 33, 11, 22]

In [6]:
lista + 2

TypeError: can only concatenate list (not "int") to list

In [7]:
lista + lista

[22, 44, 33, 11, 22, 22, 44, 33, 11, 22]

In [8]:
for i in range(len(lista)):
    lista[i] += 2
lista 

[24, 46, 35, 13, 24]