In [1]:
for i in range(10):
    print("i=", i, " binar: ", bin(i))

i= 0  binar:  0b0
i= 1  binar:  0b1
i= 2  binar:  0b10
i= 3  binar:  0b11
i= 4  binar:  0b100
i= 5  binar:  0b101
i= 6  binar:  0b110
i= 7  binar:  0b111
i= 8  binar:  0b1000
i= 9  binar:  0b1001


In [2]:
for i in range(120, 129):
    print("i=", i, " binar: ", bin(i))

i= 120  binar:  0b1111000
i= 121  binar:  0b1111001
i= 122  binar:  0b1111010
i= 123  binar:  0b1111011
i= 124  binar:  0b1111100
i= 125  binar:  0b1111101
i= 126  binar:  0b1111110
i= 127  binar:  0b1111111
i= 128  binar:  0b10000000


In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3])
print(arr, type(arr), arr.dtype)

[1 2 3] <class 'numpy.ndarray'> int64


In [5]:
arr = np.array([1, 2, 3], dtype=np.int8)
print(arr, type(arr), arr.dtype)

[1 2 3] <class 'numpy.ndarray'> int8


In [6]:
arr = np.array([1, 2, 3, 100], dtype=np.int8)
print(arr, type(arr), arr.dtype)

[  1   2   3 100] <class 'numpy.ndarray'> int8


In [7]:
arr = np.array([1, 2, 1000], dtype=np.int8)
print(arr, type(arr), arr.dtype)

OverflowError: Python integer 1000 out of bounds for int8

In [9]:
2 ** 8 - 1

255

In [10]:
arr = np.array([1, 2, 255], dtype=np.int8)
print(arr, type(arr), arr.dtype)

OverflowError: Python integer 255 out of bounds for int8

# UNSIGNED. - fara negative

In [11]:
arr = np.array([1, 2, 255], dtype=np.uint8) 
print(arr, type(arr), arr.dtype)

[  1   2 255] <class 'numpy.ndarray'> uint8


In [12]:
arr = np.array([1, 2, 256], dtype=np.uint8) 
print(arr, type(arr), arr.dtype)

OverflowError: Python integer 256 out of bounds for uint8

# int8 - numere intre -128 si 127 

In [14]:
arr = np.array([1, 2, 127], dtype=np.int8) 
print(arr, type(arr), arr.dtype)

[  1   2 127] <class 'numpy.ndarray'> int8


In [16]:
arr = np.array([1, 2, -128], dtype=np.int8) 
print(arr, type(arr), arr.dtype)

[   1    2 -128] <class 'numpy.ndarray'> int8
